//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronStore.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public int LoanId { get; set; }
        public int CashGiven { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int CustomerId { get; set; }
        public int StationLoanId { get; set; }
        public int StationCustomerId { get; set; }
        public int StatusCode { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
