//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronStore.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        public int OrderId { get; set; }
        public int ItemId { get; set; }
        public Nullable<double> WeightInKg { get; set; }
        public Nullable<double> PricePerUnit { get; set; }
        public Nullable<int> PieceCut { get; set; }
        public Nullable<int> Bundle { get; set; }
        public Nullable<double> Lengths { get; set; }
        public int OrderLineId { get; set; }
        public int StationOrderLineId { get; set; }
        public int StationOrderId { get; set; }
        public int StatusCode { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Order Order { get; set; }
    }
}
