//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronStore.ServerEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPaymentMadeServer
    {
        public int OrderPaymentMadeId { get; set; }
        public int PaymentMade { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public int StationOrderPaymentMadeId { get; set; }
        public int StationCustomerId { get; set; }
        public Nullable<int> StationOrderId { get; set; }
        public int StatusCode { get; set; }
    
        public virtual CustomerServer CustomerServer { get; set; }
        public virtual OrderServer OrderServer { get; set; }
    }
}
