//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronStore.ServerEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FaridiaIronStoreServerEntities : DbContext
    {
        public FaridiaIronStoreServerEntities()
            : base("name=FaridiaIronStoreServerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerServer> CustomerServers { get; set; }
        public virtual DbSet<ItemServer> ItemServers { get; set; }
        public virtual DbSet<LoanReturnedServer> LoanReturnedServers { get; set; }
        public virtual DbSet<LoansServer> LoansServers { get; set; }
        public virtual DbSet<LoginServer> LoginServers { get; set; }
        public virtual DbSet<OrderLineServer> OrderLineServers { get; set; }
        public virtual DbSet<OrderPaymentMadeServer> OrderPaymentMadeServers { get; set; }
        public virtual DbSet<OrderServer> OrderServers { get; set; }
        public virtual DbSet<SupplierBankDetailServer> SupplierBankDetailServers { get; set; }
        public virtual DbSet<SupplierDuePaymentsServer> SupplierDuePaymentsServers { get; set; }
        public virtual DbSet<SupplierPaymentMadeServer> SupplierPaymentMadeServers { get; set; }
        public virtual DbSet<SupplierServer> SupplierServers { get; set; }
    }
}
