//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronStore.ServerEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierServer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplierServer()
        {
            this.SupplierBankDetailServers = new HashSet<SupplierBankDetailServer>();
            this.SupplierDuePaymentsServers = new HashSet<SupplierDuePaymentsServer>();
            this.SupplierPaymentMadeServers = new HashSet<SupplierPaymentMadeServer>();
        }
    
        public int SupplierId { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public int StationSupplierId { get; set; }
        public int StatusCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierBankDetailServer> SupplierBankDetailServers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierDuePaymentsServer> SupplierDuePaymentsServers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierPaymentMadeServer> SupplierPaymentMadeServers { get; set; }
    }
}
