//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronStore.ServerEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierDuePaymentsServer
    {
        public int SupplierDuePaymentId { get; set; }
        public int AmountToBePaid { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int SupplierId { get; set; }
        public int StationSupplierDuePaymentId { get; set; }
        public int StationSupplierId { get; set; }
        public int StatusCode { get; set; }
    
        public virtual SupplierServer SupplierServer { get; set; }
    }
}
